const {
  EmbedBuilder,
  ButtonBuilder,
  ActionRowBuilder,
  ButtonStyle,
  PermissionsBitField
} = require('discord.js');
const { v4: uuidv4 } = require('uuid');
require('dotenv').config();

module.exports = {
  name: "pay",
  description: "Generate a payment invoice with QR",
  async execute(client, message, args) {
    const staffRoleId = process.env.STAFF_ROLE_ID;
    const logChannelId = process.env.PAYMENT_LOG_CHANNEL;
    const upiId = process.env.UPI_ID || "steamified@upi";
    const qrImage = process.env.QR_IMAGE || "https://i.imgur.com/your_qr_image.png";

    // Validate arguments
    if (!args.length || args.length < 2) {
      return message.reply("❌ Usage: `!pay <amount> @buyer`");
    }

    const amount = parseFloat(args[0]);
    if (isNaN(amount) || amount <= 0 || amount > 999999) {
      return message.reply("❌ Please enter a valid amount (1 - 999999).");
    }

    const buyer = message.mentions.users.first();
    if (!buyer) {
      return message.reply("❌ Please mention the buyer.");
    }

    const invoiceId = uuidv4().slice(0, 8).toUpperCase();

    const embed = new EmbedBuilder()
      .setTitle("🧾 Payment Invoice")
      .setColor("Green")
      .setThumbnail(qrImage)
      .setImage(qrImage)
      .setDescription(
        `**Invoice ID:** \`${invoiceId}\`\n` +
        `**Amount:** ₹${amount}\n` +
        `**UPI ID:** \`${upiId}\`\n` +
        `**Buyer:** ${buyer}\n\n` +
        `📥 Please scan the QR and click **Confirm Payment** once completed.`
      )
      .setFooter({ text: "Expires in 10 minutes • Payment Bot" })
      .setTimestamp();

    const confirmBtn = new ButtonBuilder()
      .setCustomId(`confirm_${invoiceId}`)
      .setLabel("✅ Confirm Payment")
      .setStyle(ButtonStyle.Success);

    const row = new ActionRowBuilder().addComponents(confirmBtn);

    let invoiceMsg;
    try {
      invoiceMsg = await message.channel.send({
        content: `🧾 Invoice generated by ${message.author}`,
        embeds: [embed],
        components: [row]
      });
    } catch (err) {
      console.error("❌ Failed to send invoice message:", err);
      return message.reply("❌ Failed to create invoice. Please try again.");
    }

    // Try deleting original command if permissions allow
    try {
      if (message.guild.members.me.permissions.has(PermissionsBitField.Flags.ManageMessages)) {
        await message.delete().catch(() => {});
      }
    } catch (err) {
      console.warn("⚠ Unable to check/delete original command message.");
    }

    // Log invoice creation
    try {
      const logChannel = await client.channels.fetch(logChannelId);
      if (!logChannel || !logChannel.isTextBased()) {
        console.warn("⚠ Log channel is not text-based or could not be found.");
      } else {
        await logChannel.send({
          content: `📥 New invoice by ${message.author}`,
          embeds: [embed]
        });
        console.log("✅ Invoice logged successfully.");
      }
    } catch (e) {
      console.warn("⚠ Failed to log invoice creation:", e);
    }

    // Button Collector
    const collector = invoiceMsg.createMessageComponentCollector({
      time: 10 * 60 * 1000
    });

    collector.on("collect", async interaction => {
      if (!interaction.member.roles.cache.has(staffRoleId)) {
        return interaction.reply({
          content: "🚫 Only staff members can confirm payments.",
          ephemeral: true
        });
      }

      if (interaction.customId === `confirm_${invoiceId}`) {
        await interaction.deferUpdate();

        const confirmEmbed = new EmbedBuilder()
          .setTitle("✅ Payment Confirmed")
          .setColor("Blue")
          .setDescription(
            `**Invoice ID:** \`${invoiceId}\`\n` +
            `**Buyer:** ${buyer}\n` +
            `**Amount:** ₹${amount}\n` +
            `**Confirmed By:** ${interaction.user}`
          )
          .setTimestamp();

        try {
          await invoiceMsg.delete();
        } catch (_) {
          console.warn("⚠ Invoice message already deleted.");
        }

        await interaction.channel.send({
          content: `✅ ${buyer}, your payment has been confirmed.`,
          embeds: [confirmEmbed]
        });

        try {
          await buyer.send({ embeds: [confirmEmbed] });
        } catch {
          console.warn("⚠ Could not DM the buyer.");
        }

        try {
          const logChannel = await client.channels.fetch(logChannelId);
          if (logChannel && logChannel.isTextBased()) {
            await logChannel.send({
              content: `📤 Invoice \`${invoiceId}\` confirmed by ${interaction.user}`,
              embeds: [confirmEmbed]
            });
          }
        } catch (_) {}

        collector.stop("confirmed");
      }
    });

    // Handle expiry
    collector.on("end", async (_, reason) => {
      if (reason !== "confirmed") {
        try {
          const fetchedMsg = await message.channel.messages.fetch(invoiceMsg.id);
          await fetchedMsg.edit({
            content: "❌ This invoice has expired.",
            embeds: [
              embed.setColor("Red").setFooter({ text: "Invoice expired." })
            ],
            components: []
          });
        } catch (e) {
          console.warn("⚠ Invoice expired but message not found or can't edit.");
        }
      }
    });
  }
};
